### ISSUE TITLE
minor issues with docs

### ISSUE THREAD

**Issue by amc94** [canonical/k8s-snap#269]
*Please describe the question or issue you're facing with "Install Canonical Kubernetes in LXD - Canonical Kubernetes documentation".*

1. lxc exec k8s -- sudo snap install k8s --classic fails because channel isn't specified
2. please link the explanation of custom lxd rules before the wget command so it'd be more easily seen
3. copying commands that have example output copies the example output as well 
i.e
```
lxc exec k8s -- sudo k8s kubectl get all

NAME                            READY   STATUS    RESTARTS   AGE
pod/microbot-6d97548556-hchb7   1/1     Running   0          21m

NAME                       TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
service/kubernetes         ClusterIP   10.152.183.1     <none>        443/TCP        21m

NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/microbot   1/1     1            1           21m

NAME                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/microbot-6d97548556   1         1         1       21m
```

---
*Reported from: https://documentation.ubuntu.com/canonical-kubernetes/latest/howto/install/lxd/*

**Comment by evilnick** [comment]
Thanks for the feedback!
3. is fixed in a current PR #272 (it is against our style guide for this exact reason)!
I will add fixes for the other 2 now

**Comment by evilnick** [comment]
It hasn't been merged yet so I actually just added the additional fixes there. thanks again.

**Comment by evilnick** [comment]
This was merged. Thanks again
