### ISSUE TITLE
Missing proxy configuration docs

### ISSUE THREAD

**Issue by VariableDeclared** [canonical/k8s-snap#315]
*Please describe the question or issue you're facing with "Install Canonical Kubernetes from a snap - Canonical Kubernetes documentation".*

Hello,

User case: Trying to setup Kubernetes in a proxied environment, I cannot see a page for proxy configuration. This issue is to capture this,

Thank you,
Peter

---
*Reported from: https://documentation.ubuntu.com/canonical-kubernetes/latest/howto/install/snap/*

**Comment by bschimke95** [comment]
Hi @VariableDeclared,

Thanks for reporting this. We'll plan to address this in the upcoming pulse.

**Comment by evilnick** [comment]
https://documentation.ubuntu.com/canonical-kubernetes/latest/snap/howto/proxy/
