### ISSUE TITLE
Proxied environment - get worker token fails - root user/lxc container

### ISSUE THREAD

**Issue by VariableDeclared** [canonical/k8s-snap#316]
*Please describe the question or issue you're facing with "Adding and Removing Nodes - Canonical Kubernetes documentation".*

Hello, 

When following the docs to setup Canonical k8s in a proxied environment I am facing an error when trying to get token from the worker node:

root@k8s-offline-node1:~# sudo k8s get-join-token worker --worker
Error: Could not generate a join token for "worker".

The error was: failed to POST /k8sd/cluster/tokens: Daemon not yet initialized

I skipped the multi-pass steps in my case, as it was not applicable,

Thank you,
Peter

---
*Reported from: https://documentation.ubuntu.com/canonical-kubernetes/latest/tutorial/add-remove-nodes/*

**Comment by bschimke95** [comment]
Hi Peter,

The error happens if the cluster is not bootstrapped. Did you run `sudo k8s bootstrap`?
Anyway, there should be a more actionable error message displayed. I'll look into why this is not the case.

**Comment by VariableDeclared** [comment]
thank you @bschimke95 I think the docs are slightly misleading, they say to bootstrap the control plane, its not clear if I need to bootstrap the worker. Indeed after running bootstrap it works - we can close if you like

**Comment by VariableDeclared** [comment]
@bschimke95 exactly, I ran on the worker, thank you for addressing this feedback!

**Comment by bschimke95** [comment]
Such feedback is highly appreciated. You just tend to take things for granted if you work on the snap on a daily basis.
