### ISSUE TITLE
kubectl alias

### ISSUE THREAD

**Issue by dulmandakh** [canonical/k8s-snap#387]
I like to create an alias to kubectl on Microk8s.
```sh
root@k8s:~# snap alias microk8s.kubectl k
Added:
  - microk8s.kubectl as k
```

But k8s fails to create an alias.

```sh
root@k8s:~# snap alias k8s.kubectl k
error: cannot perform the following tasks:
- Setup manual alias "k" => "kubectl" for snap "k8s" (cannot enable alias "k" for "k8s", target application "kubectl" does not exist)
```

I find aliases very convenient, so I don't need to install kubectl separately.

**Comment by bschimke95** [comment]
Hi @dulmandakh,

In Microk8s, kubectl is defined as a snap application, whereas in the k8s-snap, it functions as a CLI command.

We intend to introduce an automatically connected alias named kubectl in the future. In the meantime, you can utilize a bash alias to fulfill this purpose:
```
root@k8s:~# alias k="k8s kubectl"
```
