### ISSUE TITLE
k8s cannot tell if it is running in a container or a VM

### ISSUE THREAD

**Issue by jeff-hillman** [canonical/k8s-snap#439]
### Summary

When testing with LXD, unless the `--vm` flag is unsed to create an instance, the instance will start as a machine container as opposed to a VM.

There is no warning from k8s during bootstrap, or otherwise, that the system it is in doesn't have necessary lxd-profile settings required to run, which are not enabled by default.

### What Should Happen Instead?

A warning of lack of system permissions should appear

### Reproduction Steps

$ lxc launch ubuntu:24.04 k8s-test
$ lxc exec ubuntu:24.04 bash
$ snap install k8s --classic --edge
$ k8s bootstrap
$ k8s status --wait-ready  (fails)

### System information

lxd container, ubuntu 24.04

**Comment by ktsakalozos** [comment]
The merged PR should address this issue. It should be available on latest/edge. Feel free to re-open the issue if you see fit.
