### ISSUE TITLE
failed to bootstrap new cluster using POST /k8sd/cluster: failed to bootstrap new cluster: Post "http://control.socket/cluster/control": context deadline exceeded

### ISSUE THREAD

**Issue by slapcat** [canonical/k8s-snap#482]
### Summary

Bootstrapping always leads to this error: 

```
# k8s bootstrap
Bootstrapping the cluster. This may take a few seconds, please wait.
Error: Failed to bootstrap the cluster.

The error was: failed to bootstrap new cluster using POST /k8sd/cluster: failed to bootstrap new cluster: Post "http://control.socket/cluster/control": context deadline exceeded
```

In another GitHub issue, it was recommended to use a longer timeout like `--timeout 10m`, but this does not resolve it.

### What Should Happen Instead?

Bootstrap completes successfully.

### Reproduction Steps

1. sudo snap install k8s --channel=latest/edge --classic
2. sudo k8s bootstrap --timeout 10m

### System information

```
# cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
```

### Can you suggest a fix?

After the first bootstrap fails, subsequent bootstraps complain about an existing dqlite database file in `/var/snap/k8s/common/var/lib/k8s-dqlite/`. If you simply remove all files there and try to bootstrap again, it works:

```
sudo rm -r /var/snap/k8s/common/var/lib/k8s-dqlite/
```

**Comment by neoaggelos** [comment]
https://github.com/canonical/k8s-snap/pull/358/files would address this, though it was closed for unrelated reasons earlier. @bschimke95 @louiseschmidtgen I believe we should keep the cleanup bits from that PR, as they are important.

**Comment by bschimke95** [comment]
Yes, we decided to close this PR as it was stale and some parts were outdated and conflicting. Eventually, we need to pick the parts that are still relevant (e.g. the cleanup bit you mentioned) and put them into a new PR.

**Comment by ktsakalozos** [comment]
There what been a lot of work recently on fixes around the bootstrap command. We believe you should see this issue again. I am going to close this issue but please do not hesitate to reopen it if you encounter the same behavior again.

**Comment by neoaggelos** [comment]
For future clarity, this (as well as more should be addressed by changes in https://github.com/canonical/k8s-snap/pull/521
