### ISSUE TITLE
doc: Wrong parameters for the external etcd datastore bootstrap configuration

### ISSUE THREAD

**Issue by eleblebici** [canonical/k8s-snap#553]
I bootstrapped the cluster by using the below configuration file:

```
datastore-type: "external"
datastore-servers: 
  - 'https://127.0.0.1:2379'
datastore-ca-crt: |
  <etcd-root-ca-certificate>
datastore-client-crt: |
  <etcd-client-certificate>
datastore-client-key: |
  <etcd-client-key>
```

So, "datastore-type" should be used instead of "datastore", and "datastore-servers" should be used instead of "datastore-url". Also, for "datastore-servers" an array is expected. So, we should use like below:

```
 datastore-servers: 
  - 'https://127.0.0.1:2379'
```

Instead of;
`
datastore-servers: 'https://127.0.0.1:2379'`

---
Document: snap/howto/external-datastore.md

**Comment by evilnick** [comment]
Thanks for reporting this - it seems the correct set of docs were reverted as part of a larger change. Once I have dug into it I will update them to a verified example again and update here.
