### ISSUE TITLE
Docs: type already defined in configure clusterctl

### ISSUE THREAD

**Issue by amc94** [canonical/k8s-snap#653]
`providers:
  - name: ck8s
    type: BootstrapProvider
    url: "https://github.com/canonical/cluster-api-k8s/releases/latest/bootstrap-components.yaml"
  - name: ck8s
    type: ControlPlaneProvider
    url: "https://github.com/canonical/cluster-api-k8s/releases/latest/control-plane-components.yaml"
    type: "ControlPlaneProvider"` <- this shouldn't be here
---
*Reported from: https://documentation.ubuntu.com/canonical-kubernetes/latest/capi/tutorial/getting-started/*

**Comment by eaudetcobello** [comment]
Thanks for the report, I'll fix this.
