### ISSUE TITLE
docs: TYPE YOUR QUESTION HERE“IPIP”|”VXLAN”|”IPIPCrossSubnet”|”VXLANCrossSubnet”|”None”

### ISSUE THREAD

**Issue by tatality-lgtm** [canonical/k8s-snap#790]
*Please describe the question or issue you're facing with "Annotations".*

---
*Reported from: https://documentation.ubuntu.com/canonical-kubernetes/latest/src/snap/reference/annotations/*

**Comment by HomayoonAlimohammadi** [comment]
Hi @tatality-lgtm! I'm not sure I understand the issue that we have here. Would you elaborate a bit please? Thanks!

**Comment by evilnick** [comment]
If it is that the table is unreadable, we are working on that! #789

**Comment by bschimke95** [comment]
Closing this as the linked PR is merged.
