### ISSUE TITLE
doc: ImagePullBackOff after trying to side-load an OCI image

### ISSUE THREAD

**Issue by gruyaume** [canonical/k8s-snap#795]
# Description

I'm following the documentation, trying to side-load an oci image. I have created the `.tar` file, created the `/var/snap/k8s/common/images` directory (which I thought would already exist), moved the tar image there and it was not picked up automatically by containerd.

When I deploy a container that used this image, I get the usual `ImagePullBackOff` error.

Can you please provide a clear guide on how to load images?

Importing images was quite smooth with microk8s (`microk8s ctr image import`). An equivalent here would be awesome. 

## Reference
- k8s version: v1.31.2 (rev. 1593)

---
Document: src/snap/howto/install/offline.md

**Comment by gruyaume** [comment]
This still does not work for me. I copied the image to the `/var/snap/k8s/common/images/` directory but k8s didn't pick it up and I'm getting image not found errors:

```
guillaume@courge:~/code/ella$ ls /var/snap/k8s/common/images/
ella.tar
guillaume@courge:~/code/ella$ k8s list-images
ghcr.io/canonical/cilium-operator-generic:1.16.3-ck0
ghcr.io/canonical/cilium:1.16.3-ck0
ghcr.io/canonical/coredns:1.11.3-ck0
ghcr.io/canonical/k8s-snap/frrouting/frr:9.0.2
ghcr.io/canonical/k8s-snap/pause:3.10
ghcr.io/canonical/k8s-snap/sig-storage/csi-node-driver-registrar:v2.10.1
ghcr.io/canonical/k8s-snap/sig-storage/csi-provisioner:v5.0.1
ghcr.io/canonical/k8s-snap/sig-storage/csi-resizer:v1.11.1
ghcr.io/canonical/k8s-snap/sig-storage/csi-snapshotter:v8.0.1
ghcr.io/canonical/metallb-controller:v0.14.8-ck0
ghcr.io/canonical/metallb-speaker:v0.14.8-ck0
ghcr.io/canonical/metrics-server:0.7.2-ck0
ghcr.io/canonical/rawfile-localpv:0.8.0-ck4
```

```
ella-dbc46788f-rrvg4            0/1     ImagePullBackOff   0          3m1s
```

**Comment by gruyaume** [comment]
My node was already bootstrapped, do I need to restart containerd for it to capture the new images? And if yes, how can one do this?

**Comment by jneo8** [comment]
A workaround solution:

1. Find your ctr, which should under `/snap/k8s/current/bin/ctr`
2. List namespace, `/snap/k8s/current/bin/ctr namespace list`
3. List images with `/snap/k8s/current/bin/ctr --namespace k8s.io images list `
4. Import image with command: `/snap/k8s/current/bin/ctr --namespace k8s.io images import ...`
