### ISSUE TITLE
Proper Multus support

### ISSUE THREAD

**Issue by gruyaume** [canonical/k8s-snap#796]
#### Summary

At the moment, Multus support is quite awkward. As far as I know, the best approach to enable Multus in Canonical Kubernetes is to: 
1. Disable the Cilium CNI 
2. Install Multus with Helm (or another external tool)
3. Re-deploy Cilium with Helm with the "cni.exclusive" value set to false. 

#### Why is this important?

Multus is commonly used in Telco use cases.

In the context of the Telco engineering team, our User Plane Function (UPF) requires Multus. If we don't add this support, our product documentation will have to adapt from the previous Microk8s approach (microk8s enable community + microk8s enable multus) to this awkward approach. 

#### Are you interested in contributing to this feature?
It depends.

**Comment by louiseschmidtgen** [comment]
Hello @gruyaume,

Unfortunately, Canonical Kubernetes does not support community add-ons similar to MicroK8s. You will need to adjust your product documentation and install Multus via helm or another tool.

There are docs on [how-to set up Multus + SRIOV](https://documentation.ubuntu.com/canonical-kubernetes/latest/src/snap/howto/epa/#multus-and-sriov-setup) as part of our EPA docs.

Any feedback on this set-up and our documentation is welcome!

**Comment by gruyaume** [comment]
> Hello @gruyaume,
> 
> Unfortunately, Canonical Kubernetes does not support community add-ons similar to MicroK8s. You will need to adjust your product documentation and install Multus via helm or another tool.
> 
> There are docs on [how-to set up Multus + SRIOV](https://documentation.ubuntu.com/canonical-kubernetes/latest/src/snap/howto/epa/#multus-and-sriov-setup) as part of our EPA docs.
> 
> Any feedback on this set-up and our documentation is welcome!

Yeah I understand that community add-ons are a thing of the past, I'm not suggesting we take the same route as MicroK8s. I don't really mind about the approach honestly, it could be a new API, or documentation focused, but right now we have neither.

On the topic of the docs. First, they don't quite work. As I mentioned above, Cilium has to be installed with "cni.exclusive" set to false for Multus to work.  Second, they are hidden this EPA. I didn't want to "set up Enhanced Platform Awareness", all I wanted was Multus.
